### ISSUE TITLE
feat: add input field for sliders

### ISSUE THREAD

**Issue by marcgc21** [ruxailab/web-eye-tracker-front#29]

**Comment by Jaishree2310** [comment]
@marcgc21  can you provide more description? I want to take this issue.

**Comment by Jaishree2310** [comment]
> @marcgc21 can you provide more description? I want to take this issue.

@marcgc21 @KarinePistili

**Comment by KarinePistili** [comment]
@hvini @Natanco1 can you follow up this issue with @Jaishree2310 ?
