### ISSUE TITLE
Error in session record

### ISSUE THREAD

**Issue by Gaurav-Verma07** [ruxailab/web-eye-tracker-front#35]
I've facing trouble in saving the session as it just too long for loading without any result.
Steps to reproduce: 
Start a new session. 
Save the session.

![image](https://github.com/ruxailab/web-eye-tracker-front/assets/63046396/80adc4ff-6a8a-4d40-88ba-3197d6faabef)

It hangs in there without any further results.
Is it ok if it takes this long to load or am I doing anything wrong?
@marcgc21 
@KarinePistili 
Please look into this and guide me.

**Comment by Gaurav-Verma07** [comment]
Can you help me resolve this?? @marcgc21 @KarinePistili

**Comment by hvini** [comment]
Hello @Gaurav-Verma07, thanks for the interest in contributing to the project. It seems that you were trying to run the code on the main branch, which was outdated. My suggestion is to git pull the last changes and try again.

**Comment by hvini** [comment]
To test the application you should first login with your account on the login page.

![Screen Shot 2024-03-05 at 13 37 28 (2)](https://github.com/ruxailab/web-eye-tracker-front/assets/43768274/617f9ca4-90a9-4674-afa6-c0b237626e42)

Then you can start a new calibration

![Screen Shot 2024-03-05 at 13 37 38 (2)](https://github.com/ruxailab/web-eye-tracker-front/assets/43768274/c50405bd-3aaf-43f1-bc00-48a8d0883638)

Adjust your configurations according to your preferences

![Screen Shot 2024-03-05 at 13 37 43 (2)](https://github.com/ruxailab/web-eye-tracker-front/assets/43768274/c4dfe8ef-4e27-4c38-bc63-a95248b3fa92)

Press s to calibrate and finally see your results
![Screen Shot 2024-03-05 at 13 38 02 (2)](https://github.com/ruxailab/web-eye-tracker-front/assets/43768274/55db9211-929f-42c3-b7f8-d0bb4ef09e49)

![Screen Shot 2024-03-05 at 13 38 33 (2)](https://github.com/ruxailab/web-eye-tracker-front/assets/43768274/315a9094-faac-4474-be06-5b1d08766940)

You can save the calibration on the cog button

**Comment by Gaurav-Verma07** [comment]
Thanks hvini, I'll run the project again tomorrow... since my laptop is malfunctioning recently.
