### ISSUE TITLE
Post calibration UI improvement

### ISSUE THREAD

**Issue by hvini** [ruxailab/web-eye-tracker-front#36]
The cog button on post calibration page opens a modal with some operations. The problem with this modal is that it covers a big portion of the screen. The main idea of this issue is to make it open a side drawer instead of the modal, so, in this way it wont get too much in the way

![Screen Shot 2024-03-05 at 14 15 17 (2)](https://github.com/ruxailab/web-eye-tracker-front/assets/43768274/fe5c80ca-86ba-435b-af04-347eea07e57c)

**Comment by Gaurav-Verma07** [comment]
Hii @hvini :)
I've reproduced this in my local. 
This is the sample of sidebar I'm planning to implement. 
![image](https://github.com/ruxailab/web-eye-tracker-front/assets/63046396/a3eb035f-0499-40b9-907f-57a15a89c16e)
I'll do more improvements as I further into the development.
Have a look.
And please assign me this issue.

**Comment by Gaurav-Verma07** [comment]
Hi @hvini , any updates on this?

**Comment by hvini** [comment]
Hello @Gaurav-Verma07. 

for this case, with 5 points, did not covered any important data, but, if you increase the quantity of points to 6 for example, one of the points will get behind the modal. indeed sidebar will also cover some portion of screen and do not solve the problem. 

Maybe a draggable modal can solve it? but it should be clear for user that modal can be dragged.

**Comment by Gaurav-Verma07** [comment]
We can make the modal draggable but not sure if user will know if its draggable.

What if we add a draggable icon on top right of modal to indicate users that its draggable?

**Comment by hvini** [comment]
The icon is a good option, you can also change the cursor pointer to drag and/or add a "tutorial" on screen to let user known that he can drag the modal.

**Comment by Gaurav-Verma07** [comment]
THis sounds good, I'll  implement this soon.
