### ISSUE TITLE
[feat] please add a live demo link in the documentation for the live preview of how the eye-tracker front-end looks like

### ISSUE THREAD

**Issue by Tufailahmed-Bargir** [ruxailab/web-eye-tracker-front#41]
if yes please tell me , i would like to do the same

**Comment by KarinePistili** [comment]
Hello @Tufailahmed-Bargir I didn't understand the purpose of the issue.

Are you saying you would like a video showcasing the project as a whole? Like a video documentation?

Please specify a little better so we can address it ;)

**Comment by Tufailahmed-Bargir** [comment]
![image](https://github.com/ruxailab/web-eye-tracker-front/assets/142114244/c2b9331b-4337-409c-a909-85e33f99bb24)
mam in this how it is specified like live demo , same way there must be in eye tracking front-end
