### ISSUE TITLE
doc: add `VUE_APP_API_BASE_URL` in .env.example and readme

### ISSUE THREAD

**Issue by Gaurav-Verma07** [ruxailab/web-eye-tracker-front#43]
I see we are using `VUE_APP_API_BASE_URL` variable in the axios file but not declaring it in .env.example.
It'd be helpful for new contributors if we can add this.

**Comment by Gaurav-Verma07** [comment]
Hiii @hvini ,  lemme know if you want this to be added.

**Comment by KarinePistili** [comment]
Hello @Gaurav-Verma07 . Thanks for noticing.

Do you still want to work on this? Ping me if not. For now I'll have you assigned

**Comment by dakshsinghrathore** [comment]
@KarinePistili I experienced the issue mentioned here today while setting up the project locally. It's a genuine problem that could hinder new contributors. I'm keen to work on resolving this quickly to improve the onboarding experience.

**Comment by Gaurav-Verma07** [comment]
@dakshsinghrathore , a PR has already been raised. #49
